manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: anodynous
      url-base: https://github.com/anodynous
  projects:
    - name: zmk
      remote: anodynous
      revision: updated_mouse-pr_debounce 
      import: app/west.yml
  self:
    path: config
