manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: anodynous
      url-base: https://github.com/anodynous
    - name: okke-formsma
      url-base: https://github.com/okke-formsma
      name: dnaq
      url-base: https://github.com/dnaq
  projects:
    - name: zmk
      remote: dnaq
      revision: plover-hid-hog-attempt
      import: app/west.yml
  self:
    path: config
