manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: anodynous
      url-base: https://github.com/anodynous
    - name: okke-formsma
      url-base: https://github.com/okke-formsma
  projects:
    - name: zmk
      remote: anodynous
      revision: steno_macros
      import: app/west.yml
  self:
    path: config
