manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: anodynous
      url-base: https://github.com/anodynous
  projects:
    - name: zmk-original-repo
      remote: anodynous
      revision: mouse-pr_debounce
      import: app/west.yml
  self:
    path: config
